[package]
name = "voxel26"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features=["derive"] }
cgmath = "0.18.0"
env_logger = "0.11.11"
image = "0.25.10"
tokio = { version = "1.53.1", features = ["full"] }
wgpu = "30.0.0"
wgpu_text = "30.0.0"
bespoke-engine = { path = "../bespoke-engine" }
log = "0.4.33"
load_file = "1.0.1"
phf = { version = "0.14.0", features = ["macros"]}
winit = "0.30.13"
futures = "0.3.33"
noise = "0.9.0"
itertools = "0.15.0"
rand = "0.10.2"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
rustc-hash = "2.1.3"

[build-dependencies]
bespoke-engine = { path = "../bespoke-engine" }
image = "0.25.10"

[[bin]]
name = "voxel26"
path = "src/desktop.rs"

[lib]
name = "voxel26"
crate-type = ["staticlib"]
path = "src/ios.rs"

# [package.metadata.android]
# build_targets = ["armv7-linux-androideabi", "aarch64-linux-android"]
# target_sdk_version = 29
# min_sdk_version = 23
